# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc "CLI to encode, decode, and validate JWTs"
  homepage "https://github.com/compiledpanda/jwt"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/compiledpanda/jwt/releases/download/v0.2.0/jwt_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "1483e91432fe1a535a7c0df6d2b5c93025b045034b9755221c28b0b3eb7621f3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/compiledpanda/jwt/releases/download/v0.2.0/jwt_0.2.0_Linux_x86_64.tar.gz"
      sha256 "d681625fb2d618eb8cfd70c7d68e6fab0446d37db14c719159a560da3698edaf"
    end
  end
  
  head "https://github.com/compiledpanda/jwt.git"

  def install
    bin.install "jwt"
  end
end
